### ISSUE TITLE
TypeError: 'bool' object is not callable

### ISSUE THREAD

**Issue by MoranLixi** [keven1024/qinglong_helper#7]
## 开始执行... 2022-06-14 11:08:38

加载通知服务失败~

☺当前脚本目录为: /ql/data/scripts/keven1024_qinglong_helper/ql_log_scan.swap.py
😁脚本唯一性检测通过，继续运行!

Traceback (most recent call last):
  File "/ql/data/scripts/keven1024_qinglong_helper/ql_log_scan.swap.py", line 271, in <module>

    ql = QlLogScan()
  File "/ql/data/scripts/keven1024_qinglong_helper/ql_log_scan.swap.py", line 61, in __init__
    self.showAnalysisLog()
  File "/ql/data/scripts/keven1024_qinglong_helper/ql_log_scan.swap.py", line 165, in showAnalysisLog
    send("🐲青龙日志分析", result)
TypeError: 'bool' object is not callable

## 执行结束... 2022-06-14 11:08:39 耗时 1 秒

**Comment by keven1024** [comment]
猜测没有[notify.py](https://github.com/whyour/qinglong/blob/develop/sample/notify.py)文件发送通知，这个我记得从哪个版本开始青龙好像会自己添加的依赖文件。
你可以把上面的 notify.py 下载下来放到 `/ql/script/` 对应脚本目录里

**Comment by Peter-90** [comment]
在青龙面板->依赖管理->Python3下面安装requests可以解决
